### PR TITLE
maple: fix slimbus on some audio usecases

### PR DESCRIPTION
**Pull request by alviteri**
following changes
https://github.com/sonyxperiadev/device-sony-yoshino/commit/39d8acf7ad67bf9cce5ee1d9ab05d873b225d783#diff-74fc16bd814a72729b516a1988c9fda1R98

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by jerpelea** [comment]
@richardtullberg

**Comment by alviteri** [comment]
I still have not audio on wired headphones with deep-buffer low-latency .... only compress-offload

**Comment by alviteri** [comment]
this fixes it because the path was changed on yoshino as linked on commit

**Comment by richardtullberg** [comment]
@alviteri Hi, maybe its easier to change back the backend names in audio_platform_info.xml instead.
Do you want me to do that and upload it or can you do it in your commit?

BR Richard

**Comment by alviteri** [comment]
Hi Richard it should be easy to maintain slimbus6 but as you said on my comment you changed compress-offload will be affected then a change on mixer_paths will still needed ...

**Comment by richardtullberg** [comment]
@alviteri Did you have any of these issues before I changed the audio routing? Im guessing it was ok to play compressed offload content but not deep buffer low latency? And now its reversed?

**Comment by alviteri** [comment]
Before the changes wired headphones worked on all usecases now is needed this PR or come back to SLIMBUS6 on audio_platform_info .... Tell me ... I am able now to do the changes and send the PR

**Comment by richardtullberg** [comment]
@jerpelea  I am ok with his mixer path fix for now until I can understand exactly why the issue exist for us.

**Comment by alviteri** [comment]
richard the "why" is simple.... SND_DEVICE_OUT_HEADPHONES is routed now to SLIMBUS0 so none will work out this SLIMBUS but probably I am wrong ... so please double check

**Pull request merged**
