### PR TITLE
maple: increase audio capture while using camcorder source

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
ping @kholk

**Comment by kholk** [comment]
I don't know sincerely...... Maybe acdb would solve that as well?

**Comment by alviteri** [comment]
I am running under acdb .... 801 for cam ....

**Comment by alviteri** [comment]
updated commit @jerpelea with values range 20 ....

**Comment by kholk** [comment]
Then it's fine IMHO.

**Pull request merged**
