### PR TITLE
Add kernel defconfig

### PR DESCRIPTION
**Pull request by Umeaboy**
Signed-off-by: Kristoffer Grundström <hamnisdude@gmail.com>

### CODE REVIEW

**Comment by Umeaboy** [comment]
This would be useful for the o-mr1 branch as well. Does that mean that I have to open a new PR?

**Comment by oshmoun** [comment]
what does this fix/improve?

**Comment by Umeaboy** [comment]
Well, I'm building Sailfish OS which uses AOSP as base and I'm trying to build the kernel correctly.

**Comment by jerpelea** [comment]
already defined 
https://github.com/sonyxperiadev/device-sony-maple/blob/master/aosp_g8141.mk#L15

**Pull request closed without merging**
